Implement `Type is Type`
hsutter/cppfront pull request #782
Opened 2023-10-25 14:16 UTC by ntrel

This supplants #759. The same rationale applies for requiring `(identifier) is` to test an expression, see that PR for details. I added a diagnostic for `identifier is expr` where `expr` is not a type-id, because `Type is expr` is not valid - instead it will suggest using `(identifier) is`.

`cpp2util.h` changes are taken from #701 by @filipsajdak. That makes `std::runtime_error is std::exception` true, which seems correct, although I think that is not mentioned in P2392.

I had to add a `speculative` parameter to `parser::type_id()` which is `true` when there might not be a type (but an expression instead). This avoids an error for `ptr*` which is parsed as a postfix-expression from prefix-expression from is-as-expression.

2023-10-25 16:42 UTC, JohelEGP requested changes

2023-10-25 16:42 UTC, JohelEGP commented on include/cpp2util.h
> +    requires std::same_as<X, C> || std::derived_from<X,C>
```suggestion
    requires std::derived_from<X,C>
```
`std::same_as<X, C> <= std::derived_from<X, C>` (implication).

2023-10-25 16:42 UTC, JohelEGP commented on source/parse.h
> +    //GTODO     type-id is-type-constraint
```suggestion
    //G     type-id is-type-constraint
```

2023-10-26 01:31 UTC, JohelEGP commented on include/cpp2util.h
> +    requires std::same_as<X, C> || std::derived_from<X,C>
Sorry, I was wrong.
`std::same_as` can be `true` for non-class types,
whereas `std::derived_from` can only be `true` for classes.

2023-10-28 18:40 UTC, JohelEGP commented
What about the [_alternative_](https://github.com/hsutter/cppfront/issues/387#is-as-expression-target) grammar?

2023-10-30 13:36 UTC, JohelEGP commented
> I added a diagnostic for `identifier is expr` where `expr` is not a type-id, because `Type is expr` is not valid - instead it will suggest using `(identifier) is`.

If this implements <https://github.com/hsutter/cppfront/issues/358#issuecomment-1516815580>,
please add "Closes #358" to the opening comment.

2024-10-31 02:53 UTC, hsutter commented
Hi! Sorry it took me so long to get to this one. I'm going to close it as probably-dated now, but if you want to pursue it please reopen and refresh. Thanks again, and sorry again for the lag.

2024-10-31 02:53 UTC, closed without merging